include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - prefer_single_quotes
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - avoid_print
    - invocation_of_non_function_expression
analyzer:
  errors:
    invalid_annotation_target: ignore
  
    

